// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cicyivtabnlfozqctcvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpY3lpdnRhYm5sZm96cWN0Y3ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MzQ3NDYsImV4cCI6MjA2NjQxMDc0Nn0.cWbp7wxmv5QpQIO5fOmq2KAjUltT5wqZN7SqqFmPtHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);